---
# Source: teastore/templates/teastore-webui-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: teastore
    run: teastore-webui
