apiVersion: theodolite.rocks/v1beta1
kind: benchmark
metadata:
  name: teastore
spec:
  waitForResourcesEnabled: true
  sut:
    resources:
      - configMap:
          name: teastore-deployment
  loadGenerator:
    resources:
      - configMap:
          name: teastore-jmeter-deployment
  resourceTypes:
    - typeName: "Instances"
      patchers:
        - type: "ReplicaPatcher"
          resource: "teastore-auth-deployment.yaml"
        - type: "ReplicaPatcher"
          resource: "teastore-image-deployment.yaml"
        - type: "ReplicaPatcher"
          resource: "teastore-persistence-deployment.yaml"
        - type: "ReplicaPatcher"
          resource: "teastore-recommender-deployment.yaml"
        # - type: "ReplicaPatcher"
        #   resource: "teastore-registry-deployment.yaml"
        - type: "ReplicaPatcher"
          resource: "teastore-webui-deployment.yaml"
    - typeName: "InstancesWebUI"
      patchers:
        - type: "ReplicaPatcher"
          resource: "teastore-webui-deployment.yaml"
    - typeName: "PodResources"
      patchers:
        - type: "ResourceLimitPatcher"
          resource: "teastore-auth-deployment.yaml"
          properties:
            container: "teastore-auth"
            limitedResource: cpu
            format: m
        - type: "ResourceLimitPatcher"
          resource: "teastore-auth-deployment.yaml"
          properties:
            container: "teastore-auth"
            limitedResource: memory
            format: Mi
            factor: 2
        - type: "ResourceLimitPatcher"
          resource: "teastore-auth-deployment.yaml"
          properties:
            container: "teastore-auth"
            limitedResource: cpu
            format: m
        - type: "ResourceLimitPatcher"
          resource: "teastore-auth-deployment.yaml"
          properties:
            container: "teastore-auth"
            limitedResource: memory
            format: Mi
            factor: 2
        - type: "ResourceLimitPatcher"
          resource: "teastore-image-deployment.yaml"
          properties:
            container: "teastore-image"
            limitedResource: cpu
            format: m
        - type: "ResourceLimitPatcher"
          resource: "teastore-image-deployment.yaml"
          properties:
            container: "teastore-image"
            limitedResource: memory
            format: Mi
            factor: 2
        - type: "ResourceLimitPatcher"
          resource: "teastore-recommender-deployment.yaml"
          properties:
            container: "teastore-recommender"
            limitedResource: cpu
            format: m
        - type: "ResourceLimitPatcher"
          resource: "teastore-recommender-deployment.yaml"
          properties:
            container: "teastore-recommender"
            limitedResource: memory
            format: Mi
            factor: 2
        # - type: "ResourceLimitPatcher"
        #   resource: "teastore-registry-deployment.yaml"
        #   properties:
        #     container: "teastore-registry"
        #     limitedResource: cpu
        #     format: m
        # - type: "ResourceLimitPatcher"
        #   resource: "teastore-registry-deployment.yaml"
        #   properties:
        #     container: "teastore-registry"
        #     limitedResource: memory
        #     format: Mi
        #     factor: 2
        - type: "ResourceLimitPatcher"
          resource: "teastore-webui-deployment.yaml"
          properties:
            container: "teastore-webui"
            limitedResource: cpu
            format: m
        - type: "ResourceLimitPatcher"
          resource: "teastore-webui-deployment.yaml"
          properties:
            container: "teastore-webui"
            limitedResource: memory
            format: Mi
            factor: 2
  loadTypes:
    - typeName: NumUsers
      patchers:
        - type: "EnvVarPatcher"
          resource: "jmeter.yaml"
          properties:
            container: jmeter
            variableName: NUM_USERS
  slos:
    - sloType: "generic"
      name: "uiLatency"
      prometheusUrl: "http://prometheus-operated:9090"
      offset: 0
      properties:
        externalSloUrl: "http://localhost:8082"
        promQLQuery: "histogram_quantile(0.95,sum(irate(istio_request_duration_milliseconds_bucket{destination_service=~'teastore-webui.*',response_code='200'}[1m])) by (le, destination_service))"
        warmup: 300 #in seconds
        queryAggregation: max
        repetitionAggregation: median
        operator: lte
        threshold: 200
