{
 "title": "TeaStore Scalability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Latency per Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n    sum(\n        irate(\n            osm_request_duration_ms_bucket[1m]\n            )\n        )\n    by (le, destination_name)\n)",
     "legendFormat": "{{destination_name}}"
    },
    {}
   ]
  },
  {
   "title": "Incoming Requests per Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(osm_request_total[1m])) by(destination_name)",
     "legendFormat": "{{destination_name}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests per Service",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(osm_request_total[1m])) by(source_name)",
     "legendFormat": "{{source_name}}"
    }
   ]
  }
 ]
}